jobs:
  checkout_source:
    docker:
      - image: circleci/node:8.11.4-stretch
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: repository-{{ checksum ".circle-sha" }}
          paths:
            - .
  install_dependencies:
    docker:
      - image: circleci/node:8.11.4-stretch
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repository-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.11.4-stretch
      - image: rabbitmq:3.6-alpine
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repository-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
workflows:
  version: 2
  test_and_build:
    jobs:
      - checkout_source
      - install_dependencies:
          requires:
            - checkout_source
      - test:
          requires:
            - install_dependencies
